version: '3.8'

services:
    postgres:
      image: postgres
      restart: always
      environment: 
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      mem_limit: 3072m
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"] 
        interval: 5s     
        timeout: 5s     
        retries: 5       
        start_period: 10s 
      
    test:
      image: testing-app
      build:
        context: .
      container_name: testing_app_name
      working_dir: /app
      command: sh -c "npm test"
      volumes:
        - .:/app
        -  /app/node_modules
      depends_on:
        postgres:
          condition: service_healthy
      environment:
        - MODE=test
        - POSTGRES_DB=test
        - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      
volumes:
  postgres_resume_app: